# this config is adapted from Dreams of Code
# youtube link: https://www.youtube.com/@dreamsofcode
# github repo: https://github.com/dreamsofcode-io/tmux

# --- settings ---

set -g mouse on # mouse support

# make windows and pane number from 1 instead of 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# set vi-mode
set-window-option -g mode-keys vi

# --- keybindings ---

# copy mode keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# vim-like window switching
bind -n M-H previous-window
bind -n M-L next-window

# open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# set prefix key

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# --- plugins ---

set -g @plugin 'tumx-plugins/tpm' # tmux plugin manager
set -g @plugin 'tumx-plugins/tmux-sensible' # some settings that make tmux more comfortable
set -g @plugin 'christoomey/vim-tmux-navigator' # navigate through tmux panes like neovim
set -g @plugin 'catppuccin/tmux' # set tmux theme to catppuccin

# --- run tmux package manager ---

run '~/.tmux/plugins/tpm/tpm'
